Feature
ForHemer/Portfolio pull request #2
Opened 2021-11-26 19:24 UTC by ForHemer

2021-11-26 23:15 UTC, leolpaz requested changes
Hi @ForHemer , 

You've done an amazing job so far, I'd like to highlight the following:
- Repo looks professional
- PR summary is descriptive
- Template fonts were properly used

Some issues need to be resolved before your approval, but you're almost there!

![](https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Also consider:
- For the future please have a more descriptive name for your branch and PR title, "feature" is okay-ish, but it'd be better if it was the name and title of your first #1 PR 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 23:15 UTC, leolpaz commented on style.css
> +  margin: 5px;
- [ ] Great job adding margins, but as you can see in the template given by Figma (see screenshot below), the margin on the x-axis should be 24px left, kindly fix that to be more in line with the template:
![image](https://user-images.githubusercontent.com/73140461/143660106-ad079de5-43de-466a-97db-b03a2412ec1b.png)

2021-11-26 23:15 UTC, leolpaz commented on style.css
> +body {
- [ ] Kindly add `margin: 0` and possibly `padding: 0` to the body, the reason for that is because some browsers have standard behavior/styles for webpages, and specifying this, gives you more control towards how the page will look on the users' browser

2021-11-26 23:15 UTC, leolpaz commented on index.html
> +            </p>
- [ ] To be more in line with HTML best practices, kindly replace the `<p></p>` tag with an `<ul></ul>` tag, and wrap each one of the sub item images inside an`<li><a></a></li>`, as this is a list, and the images are going to be links to your social media profiles

2021-11-26 23:15 UTC, leolpaz commented on index.html
> +            <p class="connect">LET’S CONNECT</p>
- [ ] It'd be better if this was an `<a></a>` instead of a p tag, as in the future when you reach the next milestones of the project, and add more sections for your website, it can lead the user to the Contact Me part of your webpage or something related

2021-11-27 09:47 UTC, andersonlebon approved these changes
### Hi @ForHemer 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is now professional :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-27 09:47 UTC, andersonlebon commented on style.css
> +body {
# [OPTIONAL]
- [ ] Kindly work on your design by following the same  `font-family`, `font-size` `padding`, and `margins` of the template. Check the screenshot below 

Your design | The template
---------------- | -----------------
![Screenshot from 2021-11-27 11-40-25](https://user-images.githubusercontent.com/65068771/143676151-7cdb911e-e6e0-4683-8930-b5ebeb35b656.png) | ![Screenshot from 2021-11-27 11-42-17](https://user-images.githubusercontent.com/65068771/143676196-891c1e44-cdf3-4db4-8c19-2c7cef919bf3.png)

- [ ] Kindly work on it as an **important suggestion**. I know you can do it :clap: :clap:

2021-11-27 10:04 UTC, merged