Milestone: Add sections
ForHemer/Portfolio pull request #2
Opened 2021-12-03 19:51 UTC by ForHemer

The goal of this milestone is to add several sections to my portfolio website. This feature, in addition to  the home section, contains others like:

- **About myself:** A section on who am I?, my skills, etc.

2021-12-03 21:17 UTC, rotimiazeez requested changes
# Hi @ForHemer 👋, 
## Good job so far!👏
### To Highlight🔥
- No Linter errors✔
- Good PR description😉
- Good commit messages👏
- Descriptive README🔥
#### There are some issues that you still need to work on to go to the next project but you are almost there!🚀
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 21:17 UTC, rotimiazeez commented on index.html
> +                <section class="section-2">
- [ ] This section should have a `display:grid` property according to the project requirement✌

2021-12-03 21:17 UTC, rotimiazeez commented on index.html
> +                        <button>See Project</button>
- [ ] Please make sure the button follows the button styling: Active, Hover, Pressed and margin ([see design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122))✔

2021-12-03 21:17 UTC, rotimiazeez commented on index.html
> +                    <h1>About Myself</h1>
- [ ] As stated earlier please make sure you don't have more than one `h1`  tag in your code😊

2021-12-03 21:17 UTC, rotimiazeez commented on index.html
> +                    <a class="connect">LET’S CONNECT</a>
- [ ] Please note that this should use an `hx` tag `h2-h6` to match the project requirement😉

2021-12-03 23:11 UTC, petudeveloper requested changes
# Hi @ForHemer ,  👋  

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-12-03 23:11 UTC, petudeveloper commented on index.html
> +            <a class="connect">LET’S CONNECT</a>
As mentioned in the previous review this `<a><a/>` tag should be should use an `hx` tag h2-h6 to match the project requirement(If there are other titles (e.g., "Let's connect") use a header tag hx). These embedded semantics offer significant advantages 😉

2021-12-04 00:45 UTC, Gambit142 approved these changes
Hi @ForHemer 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-04 01:10 UTC, merged